### ISSUE TITLE
URGENT!

### ISSUE THREAD

**Issue by prodplug** [Berl4n/Telegram-Bot-Shop#3]
Traceback (most recent call last):
  File "C:\Users\audim\PycharmProjects\pythonProject19\app.py", line 28, in <module>
    bot = telebot.TeleBot(config.token, parse_mode=None)
TypeError: __init__() got an unexpected keyword argument 'parse_mode'

**Comment by famaxth** [comment]
Добрый день! Скорее всего ваша проблема заключается в том, что забыли установить необходимые библиотеки.
